//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _71
{

    public partial class AdminProjects
    {

        protected global::System.Web.UI.HtmlControls.HtmlForm form1;

        protected global::System.Web.UI.WebControls.LinkButton lnkLogout;

        protected global::System.Web.UI.WebControls.Panel pnlMessage;

        protected global::System.Web.UI.WebControls.Label lblMessage;

        protected global::System.Web.UI.WebControls.TextBox txtNewName;

        protected global::System.Web.UI.WebControls.TextBox txtNewImageUrl;

        protected global::System.Web.UI.WebControls.TextBox txtNewDescription;

        protected global::System.Web.UI.WebControls.DropDownList ddlNewStatus;

        protected global::System.Web.UI.WebControls.TextBox txtNewProjectUrl;

        protected global::System.Web.UI.WebControls.TextBox txtNewGithubUrl;

        protected global::System.Web.UI.WebControls.TextBox txtNewLanguage;

        protected global::System.Web.UI.WebControls.Button btnAddLanguage;

        protected global::System.Web.UI.WebControls.Repeater rptNewLanguages;

        protected global::System.Web.UI.WebControls.HiddenField hfEditProjectId;

        protected global::System.Web.UI.WebControls.Button btnAddProject;

        protected global::System.Web.UI.WebControls.Button btnUpdateProject;

        protected global::System.Web.UI.WebControls.Button btnCancelEdit;

        protected global::System.Web.UI.WebControls.Repeater rptProjects;
    }
}
