// <auto-generated>
//     This code was generated to provide strongly-typed references to controls
//     declared in the corresponding ASPX file.
// </auto-generated>
namespace _71.Admin
{

    public partial class Dashboard
    {

        protected global::System.Web.UI.WebControls.Label lblUsername;

        protected global::System.Web.UI.WebControls.Label lblProjectCount;

        protected global::System.Web.UI.WebControls.Label lblSkillCount;

        protected global::System.Web.UI.WebControls.Label lblCategoryCount;

        protected global::System.Web.UI.WebControls.Label lblMessageCount;

        protected global::System.Web.UI.WebControls.Repeater rptRecentProjects;

        protected global::System.Web.UI.WebControls.Panel pnlNoProjects;

        protected global::System.Web.UI.WebControls.Repeater rptRecentMessages;

        protected global::System.Web.UI.WebControls.Panel pnlNoMessages;
    }
}
