// <auto-generated>
namespace _71.Admin
{
    public partial class Profile
    {
        protected global::System.Web.UI.WebControls.TextBox txtName;
        protected global::System.Web.UI.WebControls.TextBox txtTitle;
        protected global::System.Web.UI.WebControls.TextBox txtEmail;
        protected global::System.Web.UI.WebControls.TextBox txtLocation;
        protected global::System.Web.UI.WebControls.TextBox txtBio;
        protected global::System.Web.UI.WebControls.TextBox txtAboutDescription;
        protected global::System.Web.UI.WebControls.TextBox txtGithub;
        protected global::System.Web.UI.WebControls.TextBox txtLinkedin;
        protected global::System.Web.UI.WebControls.Repeater rptTypewriterTexts;
        protected global::System.Web.UI.WebControls.TextBox txtNewTypewriterText;
        protected global::System.Web.UI.WebControls.Label lblMessage;
        protected global::System.Web.UI.WebControls.Panel pnlMessage;
        protected global::System.Web.UI.WebControls.Button btnSave;
        protected global::System.Web.UI.WebControls.LinkButton lnkLogout;
    }
}
