//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _71.Admin
{

    public partial class Skills
    {

        /// <summary>
        /// rptCategories control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Repeater rptCategories;

        /// <summary>
        /// txtNewCategoryName control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtNewCategoryName;

        /// <summary>
        /// lblMessage control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblMessage;

        /// <summary>
        /// pnlMessage control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Panel pnlMessage;
    }
}
